/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/Header";
import Footer from "@/components/home/Footer";
import { get } from "./actions/actions";
import { Constants } from "./constants/urls";
import MainForm from "@/components/home/MainForm"; 
import Providers from "@/store/Providers";

// Configure Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure Playfair Display
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add desired font weights
  style: ["normal", "italic"], // Add styles if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const courses = await get(Constants.courses_title);
  
  // const seodata = await get(Constants.seo);

   
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable}`}
    >
      <Providers>
        <body className="antialiased overflow-x-hidden">
          <Header />
       
          {/* <Header courses={courses} seodata={seodata}/> */}
          <MainForm  />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
